//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolaoTI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Classes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Classes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolaoTI.Resources.Classes", typeof(Classes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aposta.
        /// </summary>
        public static string Aposta_Class {
            get {
                return ResourceManager.GetString("Aposta_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonato.
        /// </summary>
        public static string Campeonato_Class {
            get {
                return ResourceManager.GetString("Campeonato_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string Claim_Class {
            get {
                return ResourceManager.GetString("Claim_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadio.
        /// </summary>
        public static string Estadio_Class {
            get {
                return ResourceManager.GetString("Estadio_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalLogin.
        /// </summary>
        public static string ExternalLogin_Class {
            get {
                return ResourceManager.GetString("ExternalLogin_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase.
        /// </summary>
        public static string Fase_Class {
            get {
                return ResourceManager.GetString("Fase_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string Grupo_Class {
            get {
                return ResourceManager.GetString("Grupo_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityRole.
        /// </summary>
        public static string IdentityRole_Class {
            get {
                return ResourceManager.GetString("IdentityRole_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityUser.
        /// </summary>
        public static string IdentityUser_Class {
            get {
                return ResourceManager.GetString("IdentityUser_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacao.
        /// </summary>
        public static string Organizacao_Class {
            get {
                return ResourceManager.GetString("Organizacao_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida.
        /// </summary>
        public static string Partida_Class {
            get {
                return ResourceManager.GetString("Partida_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil_Class {
            get {
                return ResourceManager.GetString("Perfil_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodada.
        /// </summary>
        public static string Rodada_Class {
            get {
                return ResourceManager.GetString("Rodada_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time_Class {
            get {
                return ResourceManager.GetString("Time_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario_Class {
            get {
                return ResourceManager.GetString("Usuario_Class", resourceCulture);
            }
        }
    }
}
