//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolaoTI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolaoTI.Resources.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BolaoTIContext.
        /// </summary>
        public static string BolaoTIContext {
            get {
                return ResourceManager.GetString("BolaoTIContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert-warning.
        /// </summary>
        public static string Message_Tipo_Alerta {
            get {
                return ResourceManager.GetString("Message_Tipo_Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert-danger.
        /// </summary>
        public static string Message_Tipo_Erro {
            get {
                return ResourceManager.GetString("Message_Tipo_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert-success.
        /// </summary>
        public static string Message_Tipo_Sucesso {
            get {
                return ResourceManager.GetString("Message_Tipo_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Role_Padrao_Admin {
            get {
                return ResourceManager.GetString("Role_Padrao_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participante.
        /// </summary>
        public static string Role_Padrao_Participante {
            get {
                return ResourceManager.GetString("Role_Padrao_Participante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flavio.
        /// </summary>
        public static string Usuario_Padrao_Admin {
            get {
                return ResourceManager.GetString("Usuario_Padrao_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flavioapolinario@hotmail.com.
        /// </summary>
        public static string Usuario_Padrao_Admin_Email {
            get {
                return ResourceManager.GetString("Usuario_Padrao_Admin_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apolinario@986514.
        /// </summary>
        public static string Usuario_Padrao_Admin_Senha {
            get {
                return ResourceManager.GetString("Usuario_Padrao_Admin_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (31) 99999 - 1234.
        /// </summary>
        public static string Usuario_Padrao_Admin_Telefone {
            get {
                return ResourceManager.GetString("Usuario_Padrao_Admin_Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSN - TI.
        /// </summary>
        public static string Usuario_Padrao_Organizacao {
            get {
                return ResourceManager.GetString("Usuario_Padrao_Organizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to participante.
        /// </summary>
        public static string Usuario_Padrao_Participante {
            get {
                return ResourceManager.GetString("Usuario_Padrao_Participante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to participante@bolaoti.com.
        /// </summary>
        public static string Usuario_Padrao_Participante_Email {
            get {
                return ResourceManager.GetString("Usuario_Padrao_Participante_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456.
        /// </summary>
        public static string Usuario_Padrao_Participante_Senha {
            get {
                return ResourceManager.GetString("Usuario_Padrao_Participante_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (31) 99988 - 4321.
        /// </summary>
        public static string Usuario_Padrao_Participante_Telefone {
            get {
                return ResourceManager.GetString("Usuario_Padrao_Participante_Telefone", resourceCulture);
            }
        }
    }
}
