//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolaoTI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Field {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Field() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolaoTI.Resources.Field", typeof(Field).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a nova senha.
        /// </summary>
        public static string Account_LocalPasswordModel_ConfrimPassword_Field {
            get {
                return ResourceManager.GetString("Account_LocalPasswordModel_ConfrimPassword_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar o nome para exibição.
        /// </summary>
        public static string Account_LocalPasswordModel_ExhibitionName_Field {
            get {
                return ResourceManager.GetString("Account_LocalPasswordModel_ExhibitionName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha.
        /// </summary>
        public static string Account_LocalPasswordModel_NewPassword_Field {
            get {
                return ResourceManager.GetString("Account_LocalPasswordModel_NewPassword_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual.
        /// </summary>
        public static string Account_LocalPasswordModel_OldPassword_Field {
            get {
                return ResourceManager.GetString("Account_LocalPasswordModel_OldPassword_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome para exibição.
        /// </summary>
        public static string Account_LoginModel_ExhibitionName_Field {
            get {
                return ResourceManager.GetString("Account_LoginModel_ExhibitionName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Account_LoginModel_Password_Field {
            get {
                return ResourceManager.GetString("Account_LoginModel_Password_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu sua senha?.
        /// </summary>
        public static string Account_LoginModel_RememberMe_Field {
            get {
                return ResourceManager.GetString("Account_LoginModel_RememberMe_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Account_LoginModel_UserName_Field {
            get {
                return ResourceManager.GetString("Account_LoginModel_UserName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Account_RegisterExternalLoginModel_UserName_Field {
            get {
                return ResourceManager.GetString("Account_RegisterExternalLoginModel_UserName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a senha.
        /// </summary>
        public static string Account_RegisterModel_ConfirmPassword_Field {
            get {
                return ResourceManager.GetString("Account_RegisterModel_ConfirmPassword_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome para exibição.
        /// </summary>
        public static string Account_RegisterModel_ExhibitionName_Field {
            get {
                return ResourceManager.GetString("Account_RegisterModel_ExhibitionName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Account_RegisterModel_Password_Field {
            get {
                return ResourceManager.GetString("Account_RegisterModel_Password_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Account_RegisterModel_UserName_Field {
            get {
                return ResourceManager.GetString("Account_RegisterModel_UserName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gols do time visitante.
        /// </summary>
        public static string Aposta_GolsTimeAway_Field {
            get {
                return ResourceManager.GetString("Aposta_GolsTimeAway_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gols do time da casa.
        /// </summary>
        public static string Aposta_GolsTimeHome_Field {
            get {
                return ResourceManager.GetString("Aposta_GolsTimeHome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aposta da Partida.
        /// </summary>
        public static string Aposta_PartidaAposta_Field {
            get {
                return ResourceManager.GetString("Aposta_PartidaAposta_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontos somados da aposta.
        /// </summary>
        public static string Aposta_PontosAposta_Field {
            get {
                return ResourceManager.GetString("Aposta_PontosAposta_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostador.
        /// </summary>
        public static string Aposta_Usuario_Field {
            get {
                return ResourceManager.GetString("Aposta_Usuario_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fases.
        /// </summary>
        public static string Campeonato_Fases_Field {
            get {
                return ResourceManager.GetString("Campeonato_Fases_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string Campeonato_Fim_Field {
            get {
                return ResourceManager.GetString("Campeonato_Fim_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Campeonato_Inicio_Field {
            get {
                return ResourceManager.GetString("Campeonato_Inicio_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Campeonato.
        /// </summary>
        public static string Campeonato_Nome_Field {
            get {
                return ResourceManager.GetString("Campeonato_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Abreviado.
        /// </summary>
        public static string Campeonato_NomeAbreviado_Field {
            get {
                return ResourceManager.GetString("Campeonato_NomeAbreviado_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacoes.
        /// </summary>
        public static string Campeonato_Organizacoes_Field {
            get {
                return ResourceManager.GetString("Campeonato_Organizacoes_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporada: {0} / {1}.
        /// </summary>
        public static string Campeonato_Temporada_Field {
            get {
                return ResourceManager.GetString("Campeonato_Temporada_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporada: {0}.
        /// </summary>
        public static string Campeonato_TemporadaAno_Field {
            get {
                return ResourceManager.GetString("Campeonato_TemporadaAno_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimId.
        /// </summary>
        public static string Claim_ClaimId_Field {
            get {
                return ResourceManager.GetString("Claim_ClaimId_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimType.
        /// </summary>
        public static string Claim_ClaimType_Field {
            get {
                return ResourceManager.GetString("Claim_ClaimType_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimValue.
        /// </summary>
        public static string Claim_ClaimValue_Field {
            get {
                return ResourceManager.GetString("Claim_ClaimValue_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsuarioId.
        /// </summary>
        public static string Claim_UsuarioId_Field {
            get {
                return ResourceManager.GetString("Claim_UsuarioId_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidade.
        /// </summary>
        public static string Estadio_Capacidade_Field {
            get {
                return ResourceManager.GetString("Estadio_Capacidade_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Estadio_Cidade_Field {
            get {
                return ResourceManager.GetString("Estadio_Cidade_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estadio_Estado_Field {
            get {
                return ResourceManager.GetString("Estadio_Estado_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        public static string Estadio_Localizacao_Field {
            get {
                return ResourceManager.GetString("Estadio_Localizacao_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Estadio_Nome_Field {
            get {
                return ResourceManager.GetString("Estadio_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginProvider.
        /// </summary>
        public static string ExternalLogin_LoginProvider_Field {
            get {
                return ResourceManager.GetString("ExternalLogin_LoginProvider_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProviderKey.
        /// </summary>
        public static string ExternalLogin_ProviderKey_Field {
            get {
                return ResourceManager.GetString("ExternalLogin_ProviderKey_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string ExternalLogin_UserId_Field {
            get {
                return ResourceManager.GetString("ExternalLogin_UserId_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonato.
        /// </summary>
        public static string Fase_Campeoanto_Field {
            get {
                return ResourceManager.GetString("Fase_Campeoanto_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Encerramento.
        /// </summary>
        public static string Fase_DataEncerramento_Field {
            get {
                return ResourceManager.GetString("Fase_DataEncerramento_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Fase_Nome_Field {
            get {
                return ResourceManager.GetString("Fase_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Fase_Situacao_Field {
            get {
                return ResourceManager.GetString("Fase_Situacao_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase do Grupo.
        /// </summary>
        public static string Grupo_Fase_Field {
            get {
                return ResourceManager.GetString("Grupo_Fase_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Grupo.
        /// </summary>
        public static string Grupo_Nome_Field {
            get {
                return ResourceManager.GetString("Grupo_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodadas do Grupo.
        /// </summary>
        public static string Grupo_Rodadas_Field {
            get {
                return ResourceManager.GetString("Grupo_Rodadas_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonatos.
        /// </summary>
        public static string Organizacao_Campeonato_Field {
            get {
                return ResourceManager.GetString("Organizacao_Campeonato_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Organizacao_Nome_Field {
            get {
                return ResourceManager.GetString("Organizacao_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Organizacao_Usuario_Field {
            get {
                return ResourceManager.GetString("Organizacao_Usuario_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostas da Partida.
        /// </summary>
        public static string Partida_Apostas_Field {
            get {
                return ResourceManager.GetString("Partida_Apostas_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Partida.
        /// </summary>
        public static string Partida_DataPartida_Field {
            get {
                return ResourceManager.GetString("Partida_DataPartida_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empate.
        /// </summary>
        public static string Partida_Empate_Field {
            get {
                return ResourceManager.GetString("Partida_Empate_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadio.
        /// </summary>
        public static string Partida_Estadio_Field {
            get {
                return ResourceManager.GetString("Partida_Estadio_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodada - Grupo.
        /// </summary>
        public static string Partida_GrupoRodada_Field {
            get {
                return ResourceManager.GetString("Partida_GrupoRodada_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodada.
        /// </summary>
        public static string Partida_Rodada_Field {
            get {
                return ResourceManager.GetString("Partida_Rodada_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeAway.
        /// </summary>
        public static string Partida_TimeAway_Field {
            get {
                return ResourceManager.GetString("Partida_TimeAway_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gols Time Casa.
        /// </summary>
        public static string Partida_TimeCasa_Gols_Field {
            get {
                return ResourceManager.GetString("Partida_TimeCasa_Gols_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Casa.
        /// </summary>
        public static string Partida_TimeCasa_Nome_Field {
            get {
                return ResourceManager.GetString("Partida_TimeCasa_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeHome.
        /// </summary>
        public static string Partida_TimeHome_Field {
            get {
                return ResourceManager.GetString("Partida_TimeHome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gols Time Visitante.
        /// </summary>
        public static string Partida_TimeVisitante_Gols_Field {
            get {
                return ResourceManager.GetString("Partida_TimeVisitante_Gols_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Visitante.
        /// </summary>
        public static string Partida_TimeVisitante_Nome_Field {
            get {
                return ResourceManager.GetString("Partida_TimeVisitante_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfilId.
        /// </summary>
        public static string Perfil_Id_Field {
            get {
                return ResourceManager.GetString("Perfil_Id_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Perfil_Nome_Field {
            get {
                return ResourceManager.GetString("Perfil_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colocação.
        /// </summary>
        public static string Ranking_Colocacao_Field {
            get {
                return ResourceManager.GetString("Ranking_Colocacao_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalPontos.
        /// </summary>
        public static string Ranking_TotalPontos_Field {
            get {
                return ResourceManager.GetString("Ranking_TotalPontos_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participante.
        /// </summary>
        public static string Ranking_Usuario_Nome_Field {
            get {
                return ResourceManager.GetString("Ranking_Usuario_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodada do Grupo.
        /// </summary>
        public static string Rodada_Grupo_Field {
            get {
                return ResourceManager.GetString("Rodada_Grupo_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodada.
        /// </summary>
        public static string Rodada_Nome_Field {
            get {
                return ResourceManager.GetString("Rodada_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas.
        /// </summary>
        public static string Rodada_Partidas_Field {
            get {
                return ResourceManager.GetString("Rodada_Partidas_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeira.
        /// </summary>
        public static string Time_Bandeira_Field {
            get {
                return ResourceManager.GetString("Time_Bandeira_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Time_Nome_Field {
            get {
                return ResourceManager.GetString("Time_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Abreviado.
        /// </summary>
        public static string Time_NomeAbreviado_Field {
            get {
                return ResourceManager.GetString("Time_NomeAbreviado_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        public static string Usuario_Claims_Field {
            get {
                return ResourceManager.GetString("Usuario_Claims_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a Nova Senha.
        /// </summary>
        public static string Usuario_ConfimNewPassword_Field {
            get {
                return ResourceManager.GetString("Usuario_ConfimNewPassword_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a Senha.
        /// </summary>
        public static string Usuario_ConfimPassword_Field {
            get {
                return ResourceManager.GetString("Usuario_ConfimPassword_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Usuario_Email_Field {
            get {
                return ResourceManager.GetString("Usuario_Email_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalLogins.
        /// </summary>
        public static string Usuario_ExternalLogins_Field {
            get {
                return ResourceManager.GetString("Usuario_ExternalLogins_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsuarioId.
        /// </summary>
        public static string Usuario_Id_Field {
            get {
                return ResourceManager.GetString("Usuario_Id_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string Usuario_NewPassword_Field {
            get {
                return ResourceManager.GetString("Usuario_NewPassword_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participante.
        /// </summary>
        public static string Usuario_Nome_Field {
            get {
                return ResourceManager.GetString("Usuario_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome para exibição.
        /// </summary>
        public static string Usuario_NomeExibicao_Field {
            get {
                return ResourceManager.GetString("Usuario_NomeExibicao_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Antiga.
        /// </summary>
        public static string Usuario_OldPassword_Field {
            get {
                return ResourceManager.GetString("Usuario_OldPassword_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacoes.
        /// </summary>
        public static string Usuario_Organizacoes_Field {
            get {
                return ResourceManager.GetString("Usuario_Organizacoes_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Usuario_Password_Field {
            get {
                return ResourceManager.GetString("Usuario_Password_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordHash.
        /// </summary>
        public static string Usuario_PasswordHash_Field {
            get {
                return ResourceManager.GetString("Usuario_PasswordHash_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Usuario_Perfil_Field {
            get {
                return ResourceManager.GetString("Usuario_Perfil_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfis.
        /// </summary>
        public static string Usuario_Perfils_Field {
            get {
                return ResourceManager.GetString("Usuario_Perfils_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityStamp.
        /// </summary>
        public static string Usuario_SecurityStamp_Field {
            get {
                return ResourceManager.GetString("Usuario_SecurityStamp_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Usuario_Telefone_Field {
            get {
                return ResourceManager.GetString("Usuario_Telefone_Field", resourceCulture);
            }
        }
    }
}
