//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolaoTI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolaoTI.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem Gols.
        /// </summary>
        public static string AlertMessage_Aposta_SemGols {
            get {
                return ResourceManager.GetString("AlertMessage_Aposta_SemGols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Nº de gols.
        /// </summary>
        public static string AlertMessage_Informe_NumeroGols {
            get {
                return ResourceManager.GetString("AlertMessage_Informe_NumeroGols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um {0}: {1} associado a organização..
        /// </summary>
        public static string AlertMessage_Organizacao_Registro_Associado {
            get {
                return ResourceManager.GetString("AlertMessage_Organizacao_Registro_Associado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma partida entre {0}  x {1} na data: {2}.
        /// </summary>
        public static string AlertMessage_Partida_Existente {
            get {
                return ResourceManager.GetString("AlertMessage_Partida_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um(a) {0} com {1} : [ {2} ].
        /// </summary>
        public static string AlertMessage_Registro_Existente {
            get {
                return ResourceManager.GetString("AlertMessage_Registro_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} deve ser de pelo menos {2} caracteres.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha e a senha de confirmação não coincidem..
        /// </summary>
        public static string ErrorMessage_Account_LocalPasswordModel_DiferenceBetweenPasswordAndConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorMessage_Account_LocalPasswordModel_DiferenceBetweenPasswordAndConfirmPasswor" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ter, pelo menos, {1} caracteres..
        /// </summary>
        public static string ErrorMessage_Account_LocalPasswordModel_LengthPassword {
            get {
                return ResourceManager.GetString("ErrorMessage_Account_LocalPasswordModel_LengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} não encontrada para realizar o calculo dos pontos&quot;.
        /// </summary>
        public static string ErrorMessage_CalculoPontos_SemAposta_e_Partida {
            get {
                return ResourceManager.GetString("ErrorMessage_CalculoPontos_SemAposta_e_Partida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} não correspondem a uma entidade de {1}..
        /// </summary>
        public static string ErrorMessage_Classe_Nao_Corresponde_Entidade {
            get {
                return ResourceManager.GetString("ErrorMessage_Classe_Nao_Corresponde_Entidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não é um endereço válido de email.
        /// </summary>
        public static string ErrorMessage_Comum_EmailInvalidoField {
            get {
                return ResourceManager.GetString("ErrorMessage_Comum_EmailInvalidoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo {0}!.
        /// </summary>
        public static string ErrorMessage_Comum_EmptyField {
            get {
                return ResourceManager.GetString("ErrorMessage_Comum_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade invalida do Objeto..
        /// </summary>
        public static string ErrorMessage_Field_Propriedade_Invalida_Objeto {
            get {
                return ResourceManager.GetString("ErrorMessage_Field_Propriedade_Invalida_Objeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} atributo deve ser definido no membro {1}..
        /// </summary>
        public static string ErrorMessage_FieldUtil_Atributo_NaoDefinido_Membro {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldUtil_Atributo_NaoDefinido_Membro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membro &apos;{0}&apos; não encontrado no tipo  &apos;{1}&apos;.
        /// </summary>
        public static string ErrorMessage_FieldUtil_MembroNaoEncontrado_NoTipoInformado {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldUtil_MembroNaoEncontrado_NoTipoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}.{1}&apos; Objeto nao tem DisplayAttribute.
        /// </summary>
        public static string ErrorMessage_FieldUtil_ObjetoNaoPossuiDisplayAttribute {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldUtil_ObjetoNaoPossuiDisplayAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo &apos;{0}&apos; não é um Enum..
        /// </summary>
        public static string ErrorMessage_FieldUtil_TipoObjeto_DiferenteEnum {
            get {
                return ResourceManager.GetString("ErrorMessage_FieldUtil_TipoObjeto_DiferenteEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato invalido.
        /// </summary>
        public static string ErrorMessage_FormatoInvalido {
            get {
                return ResourceManager.GetString("ErrorMessage_FormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametro nao pode ser NULL, VAZIO ou ESPAÇO EM BRANCO: {0}.
        /// </summary>
        public static string ErrorMessage_Parametro_Vazio {
            get {
                return ResourceManager.GetString("ErrorMessage_Parametro_Vazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do time deve ter no maximo {0} caracteres..
        /// </summary>
        public static string ErrorMessage_Time_TamanhoNome {
            get {
                return ResourceManager.GetString("ErrorMessage_Time_TamanhoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome abreviado do time deve ter no maximo {0} caracteres..
        /// </summary>
        public static string ErrorMessage_Time_TamanhoNomeAbreviado {
            get {
                return ResourceManager.GetString("ErrorMessage_Time_TamanhoNomeAbreviado", resourceCulture);
            }
        }
    }
}
