//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolaoTI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolaoTI.Resources.Tables", typeof(Tables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOLS_TIME_AWAY.
        /// </summary>
        public static string Aposta_GolsTimeAway_ColumnName {
            get {
                return ResourceManager.GetString("Aposta_GolsTimeAway_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOLS_TIME_HOME.
        /// </summary>
        public static string Aposta_GolsTimeHome_ColumnName {
            get {
                return ResourceManager.GetString("Aposta_GolsTimeHome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APOSTA_ID.
        /// </summary>
        public static string Aposta_Id_ColumnName {
            get {
                return ResourceManager.GetString("Aposta_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIDA_ID.
        /// </summary>
        public static string Aposta_PartidaId_ColumnName {
            get {
                return ResourceManager.GetString("Aposta_PartidaId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PONTOS_APOSTA.
        /// </summary>
        public static string Aposta_PontosAposta_ColumnName {
            get {
                return ResourceManager.GetString("Aposta_PontosAposta_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APOSTA.
        /// </summary>
        public static string Aposta_Table {
            get {
                return ResourceManager.GetString("Aposta_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO_ID.
        /// </summary>
        public static string Aposta_UsuarioId_ColumnName {
            get {
                return ResourceManager.GetString("Aposta_UsuarioId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Campeoanto_Nome_ColumnName {
            get {
                return ResourceManager.GetString("Campeoanto_Nome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIM.
        /// </summary>
        public static string Campeonato_Fim_ColumnName {
            get {
                return ResourceManager.GetString("Campeonato_Fim_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPEONATO_ID.
        /// </summary>
        public static string Campeonato_Id_ColumnName {
            get {
                return ResourceManager.GetString("Campeonato_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIO.
        /// </summary>
        public static string Campeonato_Inicio_ColumnName {
            get {
                return ResourceManager.GetString("Campeonato_Inicio_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME_ABREVIADO.
        /// </summary>
        public static string Campeonato_NomeAbreviado_ColumnName {
            get {
                return ResourceManager.GetString("Campeonato_NomeAbreviado_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPEONATO.
        /// </summary>
        public static string Campeonato_Table {
            get {
                return ResourceManager.GetString("Campeonato_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPEONATO_ID.
        /// </summary>
        public static string CampeonatoOrganizacao_CampeonatoId_FK_Column {
            get {
                return ResourceManager.GetString("CampeonatoOrganizacao_CampeonatoId_FK_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZACAO_ID.
        /// </summary>
        public static string CampeonatoOrganizacao_OrganizacaoId_FK_Column {
            get {
                return ResourceManager.GetString("CampeonatoOrganizacao_OrganizacaoId_FK_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPEONATO_ORGANIZACAO.
        /// </summary>
        public static string CampeonatoOrganizacao_Table {
            get {
                return ResourceManager.GetString("CampeonatoOrganizacao_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLAIM_ID.
        /// </summary>
        public static string Claim_ClaimId_ColumnName {
            get {
                return ResourceManager.GetString("Claim_ClaimId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLAIM_TYPE.
        /// </summary>
        public static string Claim_ClaimType_ColumnName {
            get {
                return ResourceManager.GetString("Claim_ClaimType_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLAIM_VALUE.
        /// </summary>
        public static string Claim_ClaimValue_ColumnName {
            get {
                return ResourceManager.GetString("Claim_ClaimValue_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLAIM.
        /// </summary>
        public static string Claim_Table {
            get {
                return ResourceManager.GetString("Claim_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO_ID.
        /// </summary>
        public static string Claim_UsuarioId_ColumnName {
            get {
                return ResourceManager.GetString("Claim_UsuarioId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPACIDADE.
        /// </summary>
        public static string Estadio_Capacidade_ColumnName {
            get {
                return ResourceManager.GetString("Estadio_Capacidade_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIDADE.
        /// </summary>
        public static string Estadio_Cidade_ColumnName {
            get {
                return ResourceManager.GetString("Estadio_Cidade_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADIO_ID.
        /// </summary>
        public static string Estadio_Id_ColumnName {
            get {
                return ResourceManager.GetString("Estadio_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Estadio_Nome_ColumnName {
            get {
                return ResourceManager.GetString("Estadio_Nome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADIO.
        /// </summary>
        public static string Estadio_Table {
            get {
                return ResourceManager.GetString("Estadio_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string Estadio_UF_ColumnName {
            get {
                return ResourceManager.GetString("Estadio_UF_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTERNAL_LOGIN.
        /// </summary>
        public static string ExternalLogin {
            get {
                return ResourceManager.GetString("ExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN_PROVIDER.
        /// </summary>
        public static string ExternalLogin_LoginProvider_ColumnName {
            get {
                return ResourceManager.GetString("ExternalLogin_LoginProvider_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROVIDER_KEY.
        /// </summary>
        public static string ExternalLogin_ProviderKey_ColumnName {
            get {
                return ResourceManager.GetString("ExternalLogin_ProviderKey_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO_ID.
        /// </summary>
        public static string ExternalLogin_UserId_ColumnName {
            get {
                return ResourceManager.GetString("ExternalLogin_UserId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPEONATO_ID.
        /// </summary>
        public static string Fase_CampeonatoId_ColumnName {
            get {
                return ResourceManager.GetString("Fase_CampeonatoId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_FIM.
        /// </summary>
        public static string Fase_DataFim_ColumnName {
            get {
                return ResourceManager.GetString("Fase_DataFim_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_INICIO.
        /// </summary>
        public static string Fase_DataInicio_ColumnName {
            get {
                return ResourceManager.GetString("Fase_DataInicio_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FASE_ID.
        /// </summary>
        public static string Fase_Id_ColumnName {
            get {
                return ResourceManager.GetString("Fase_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Fase_Nome_ColumnName {
            get {
                return ResourceManager.GetString("Fase_Nome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FASE.
        /// </summary>
        public static string Fase_Table {
            get {
                return ResourceManager.GetString("Fase_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FASE_ID.
        /// </summary>
        public static string Grupo_FaseId_ColumnName {
            get {
                return ResourceManager.GetString("Grupo_FaseId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRUPO_ID.
        /// </summary>
        public static string Grupo_Id_ColumnName {
            get {
                return ResourceManager.GetString("Grupo_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Grupo_Nome_ColumnName {
            get {
                return ResourceManager.GetString("Grupo_Nome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRUPO.
        /// </summary>
        public static string Grupo_Table {
            get {
                return ResourceManager.GetString("Grupo_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZACAO_ID.
        /// </summary>
        public static string Organizacao_Id_ColumnName {
            get {
                return ResourceManager.GetString("Organizacao_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Organizacao_Nome_ColumnName {
            get {
                return ResourceManager.GetString("Organizacao_Nome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZACAO.
        /// </summary>
        public static string Organizacao_Table {
            get {
                return ResourceManager.GetString("Organizacao_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_PARTIDA.
        /// </summary>
        public static string Partida_DataPartida_ColumnName {
            get {
                return ResourceManager.GetString("Partida_DataPartida_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADIO_ID.
        /// </summary>
        public static string Partida_EstadioId_ColumnName {
            get {
                return ResourceManager.GetString("Partida_EstadioId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOLS_TIME_AWAY.
        /// </summary>
        public static string Partida_GolsTimeAway_ColumnName {
            get {
                return ResourceManager.GetString("Partida_GolsTimeAway_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOLS_TIME_HOME.
        /// </summary>
        public static string Partida_GolsTimeHome_ColumnName {
            get {
                return ResourceManager.GetString("Partida_GolsTimeHome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIDA_ID.
        /// </summary>
        public static string Partida_Id_ColumnName {
            get {
                return ResourceManager.GetString("Partida_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RODADA_ID.
        /// </summary>
        public static string Partida_RodadaId_ColumnName {
            get {
                return ResourceManager.GetString("Partida_RodadaId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIDA.
        /// </summary>
        public static string Partida_Table {
            get {
                return ResourceManager.GetString("Partida_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME_AWAY_ID.
        /// </summary>
        public static string Partida_TimeAwayId_ColumnName {
            get {
                return ResourceManager.GetString("Partida_TimeAwayId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME_HOME_ID.
        /// </summary>
        public static string Partida_TimeHomeId_ColumnName {
            get {
                return ResourceManager.GetString("Partida_TimeHomeId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFIL_ID.
        /// </summary>
        public static string Perfil_Id_Field {
            get {
                return ResourceManager.GetString("Perfil_Id_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Perfil_Nome_Field {
            get {
                return ResourceManager.GetString("Perfil_Nome_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFIL.
        /// </summary>
        public static string Perfil_Table {
            get {
                return ResourceManager.GetString("Perfil_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPEONATO_ID.
        /// </summary>
        public static string Ranking_CampeonatoId_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_CampeonatoId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CINCO_TOTAL_PONTOS.
        /// </summary>
        public static string Ranking_CincoTotalPontos_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_CincoTotalPontos_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLOCACAO.
        /// </summary>
        public static string Ranking_Colocacao_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_Colocacao_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEZ_TOTAL_PONTOS.
        /// </summary>
        public static string Ranking_DezTotalPontos_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_DezTotalPontos_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOIS_TOTAL_PONTOS.
        /// </summary>
        public static string Ranking_DoisTotalPontos_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_DoisTotalPontos_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANKING_ID.
        /// </summary>
        public static string Ranking_Id_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMERO_APOSTAS.
        /// </summary>
        public static string Ranking_NumeroApostas_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_NumeroApostas_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMERO_PARTIDAS.
        /// </summary>
        public static string Ranking_NumeroPartidas_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_NumeroPartidas_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZACAO_ID.
        /// </summary>
        public static string Ranking_OrganizacaoId_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_OrganizacaoId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETE_TOTAL_PONTOS.
        /// </summary>
        public static string Ranking_SeteTotalPontos_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_SeteTotalPontos_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANKING.
        /// </summary>
        public static string Ranking_Table {
            get {
                return ResourceManager.GetString("Ranking_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL_PONTOS.
        /// </summary>
        public static string Ranking_TotalPontos_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_TotalPontos_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO_ID.
        /// </summary>
        public static string Ranking_UsuarioId_ColumnName {
            get {
                return ResourceManager.GetString("Ranking_UsuarioId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRUPO_ID.
        /// </summary>
        public static string Rodada_GrupoId_ColumnName {
            get {
                return ResourceManager.GetString("Rodada_GrupoId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RODADA_ID.
        /// </summary>
        public static string Rodada_Id_ColumnName {
            get {
                return ResourceManager.GetString("Rodada_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Rodada_Nome_ColumnName {
            get {
                return ResourceManager.GetString("Rodada_Nome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDEM.
        /// </summary>
        public static string Rodada_Ordem_ColumnName {
            get {
                return ResourceManager.GetString("Rodada_Ordem_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RODADA.
        /// </summary>
        public static string Rodada_Table {
            get {
                return ResourceManager.GetString("Rodada_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME_ID.
        /// </summary>
        public static string Time_Id_ColumnName {
            get {
                return ResourceManager.GetString("Time_Id_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMINHO_IMAGEM_BANDEIRA.
        /// </summary>
        public static string Time_ImagemBandeira_ColumnName {
            get {
                return ResourceManager.GetString("Time_ImagemBandeira_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Time_Nome_ColumnName {
            get {
                return ResourceManager.GetString("Time_Nome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME_ABREVIADO.
        /// </summary>
        public static string Time_NomeAbreviado_ColumnName {
            get {
                return ResourceManager.GetString("Time_NomeAbreviado_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        public static string Time_Table {
            get {
                return ResourceManager.GetString("Time_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string Tipo_Coluna_Date {
            get {
                return ResourceManager.GetString("Tipo_Coluna_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datetime2.
        /// </summary>
        public static string Tipo_Coluna_DateTime {
            get {
                return ResourceManager.GetString("Tipo_Coluna_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int.
        /// </summary>
        public static string Tipo_Coluna_Int {
            get {
                return ResourceManager.GetString("Tipo_Coluna_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvarchar.
        /// </summary>
        public static string Tipo_Coluna_NVarchar {
            get {
                return ResourceManager.GetString("Tipo_Coluna_NVarchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uniqueidentifier.
        /// </summary>
        public static string Tipo_Coluna_UniqueIdentifier {
            get {
                return ResourceManager.GetString("Tipo_Coluna_UniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string Usuario_Email_ColumnName {
            get {
                return ResourceManager.GetString("Usuario_Email_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Usuario_Nome_ColumnName {
            get {
                return ResourceManager.GetString("Usuario_Nome_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_HASH.
        /// </summary>
        public static string Usuario_PasswordHash_ColumnName {
            get {
                return ResourceManager.GetString("Usuario_PasswordHash_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECURITY_STAMP.
        /// </summary>
        public static string Usuario_SecurityStamp_ColumnName {
            get {
                return ResourceManager.GetString("Usuario_SecurityStamp_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO.
        /// </summary>
        public static string Usuario_Table {
            get {
                return ResourceManager.GetString("Usuario_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELEFONE.
        /// </summary>
        public static string Usuario_Telefone_ColumnName {
            get {
                return ResourceManager.GetString("Usuario_Telefone_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO_ID.
        /// </summary>
        public static string Usuario_UsuarioId_ColumnName {
            get {
                return ResourceManager.GetString("Usuario_UsuarioId_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZACAO_ID.
        /// </summary>
        public static string UsuarioOrganizacao_OrganizacaoId_FK_Column {
            get {
                return ResourceManager.GetString("UsuarioOrganizacao_OrganizacaoId_FK_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO_ORGANIZACAO.
        /// </summary>
        public static string UsuarioOrganizacao_Table {
            get {
                return ResourceManager.GetString("UsuarioOrganizacao_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO_ID.
        /// </summary>
        public static string UsuarioOrganizacao_UsuarioId_FK_Column {
            get {
                return ResourceManager.GetString("UsuarioOrganizacao_UsuarioId_FK_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFIL_ID.
        /// </summary>
        public static string UsuarioPerfil_PerfilId_FK_Column {
            get {
                return ResourceManager.GetString("UsuarioPerfil_PerfilId_FK_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO_PERFIL.
        /// </summary>
        public static string UsuarioPerfil_Table {
            get {
                return ResourceManager.GetString("UsuarioPerfil_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO_ID.
        /// </summary>
        public static string UsuarioPerfil_UsuarioId_FK_Column {
            get {
                return ResourceManager.GetString("UsuarioPerfil_UsuarioId_FK_Column", resourceCulture);
            }
        }
    }
}
