//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolaoTI.Resources.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolaoTI.Resources.View.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        public static string Label_Cadastrar {
            get {
                return ResourceManager.GetString("Label_Cadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando....
        /// </summary>
        public static string Label_Carregando {
            get {
                return ResourceManager.GetString("Label_Carregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Label_Configuracoes {
            get {
                return ResourceManager.GetString("Label_Configuracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar nova conta..
        /// </summary>
        public static string Label_Criar_Conta {
            get {
                return ResourceManager.GetString("Label_Criar_Conta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de Senha.
        /// </summary>
        public static string Label_FormAlteracaoSenha {
            get {
                return ResourceManager.GetString("Label_FormAlteracaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar.
        /// </summary>
        public static string Label_Gerenciar_Usuarios {
            get {
                return ResourceManager.GetString("Label_Gerenciar_Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está logado como.
        /// </summary>
        public static string Label_LogadoComo {
            get {
                return ResourceManager.GetString("Label_LogadoComo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazer Login.
        /// </summary>
        public static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazer Logoff.
        /// </summary>
        public static string Label_LogOff {
            get {
                return ResourceManager.GetString("Label_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudar Senha.
        /// </summary>
        public static string Label_Mudar_Senha {
            get {
                return ResourceManager.GetString("Label_Mudar_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se você não possui conta..
        /// </summary>
        public static string Label_Nao_Possui_Conta {
            get {
                return ResourceManager.GetString("Label_Nao_Possui_Conta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Label_Quantidade {
            get {
                return ResourceManager.GetString("Label_Quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Label_Ranking {
            get {
                return ResourceManager.GetString("Label_Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonato.
        /// </summary>
        public static string Label_Selecione_Campeonato {
            get {
                return ResourceManager.GetString("Label_Selecione_Campeonato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase.
        /// </summary>
        public static string Label_Selecione_Fase {
            get {
                return ResourceManager.GetString("Label_Selecione_Fase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organização.
        /// </summary>
        public static string Label_Selecione_Organizacao {
            get {
                return ResourceManager.GetString("Label_Selecione_Organizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolão TI.
        /// </summary>
        public static string Label_Titulo_BolaoTI {
            get {
                return ResourceManager.GetString("Label_Titulo_BolaoTI", resourceCulture);
            }
        }
    }
}
