//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolaoTI.Resources.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Link {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Link() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolaoTI.Resources.View.Link", typeof(Link).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Participante.
        /// </summary>
        public static string Action_AddParticipante_Link {
            get {
                return ResourceManager.GetString("Action_AddParticipante_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostar.
        /// </summary>
        public static string Action_Apostar_link {
            get {
                return ResourceManager.GetString("Action_Apostar_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Action_Editar_Link {
            get {
                return ResourceManager.GetString("Action_Editar_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar Partida.
        /// </summary>
        public static string Action_FecharPartida_link {
            get {
                return ResourceManager.GetString("Action_FecharPartida_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Action_Index_Link {
            get {
                return ResourceManager.GetString("Action_Index_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string Action_Novo_Link {
            get {
                return ResourceManager.GetString("Action_Novo_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas.
        /// </summary>
        public static string Action_Partidas_Link {
            get {
                return ResourceManager.GetString("Action_Partidas_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Action_Pesquisar_Link {
            get {
                return ResourceManager.GetString("Action_Pesquisar_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Action_Remover_Link {
            get {
                return ResourceManager.GetString("Action_Remover_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar Senha.
        /// </summary>
        public static string Action_Reset_Link {
            get {
                return ResourceManager.GetString("Action_Reset_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Action_Salvar_link {
            get {
                return ResourceManager.GetString("Action_Salvar_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Action_Voltar_Link {
            get {
                return ResourceManager.GetString("Action_Voltar_Link", resourceCulture);
            }
        }
    }
}
