//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolaoTI.Resources.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolaoTI.Resources.View.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeonatos.
        /// </summary>
        public static string Admin_Campeonato_menu {
            get {
                return ResourceManager.GetString("Admin_Campeonato_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadios.
        /// </summary>
        public static string Admin_Estadio_menu {
            get {
                return ResourceManager.GetString("Admin_Estadio_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fases.
        /// </summary>
        public static string Admin_Fase_menu {
            get {
                return ResourceManager.GetString("Admin_Fase_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar Fase.
        /// </summary>
        public static string Admin_FecharFase_menu {
            get {
                return ResourceManager.GetString("Admin_FecharFase_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar Partidas.
        /// </summary>
        public static string Admin_FecharPartida_menu {
            get {
                return ResourceManager.GetString("Admin_FecharPartida_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos.
        /// </summary>
        public static string Admin_Grupo_menu {
            get {
                return ResourceManager.GetString("Admin_Grupo_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizações.
        /// </summary>
        public static string Admin_Organizacao_menu {
            get {
                return ResourceManager.GetString("Admin_Organizacao_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfis.
        /// </summary>
        public static string Admin_Perfil_menu {
            get {
                return ResourceManager.GetString("Admin_Perfil_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string Admin_Time_menu {
            get {
                return ResourceManager.GetString("Admin_Time_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Admin_Usuario_menu {
            get {
                return ResourceManager.GetString("Admin_Usuario_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administração.
        /// </summary>
        public static string Home_Admin_menu {
            get {
                return ResourceManager.GetString("Home_Admin_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostas.
        /// </summary>
        public static string Home_Aposta_menu {
            get {
                return ResourceManager.GetString("Home_Aposta_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Inicial_menu {
            get {
                return ResourceManager.GetString("Home_Inicial_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Home_Ranking_menu {
            get {
                return ResourceManager.GetString("Home_Ranking_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regras.
        /// </summary>
        public static string Home_Regras_menu {
            get {
                return ResourceManager.GetString("Home_Regras_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de Jogos.
        /// </summary>
        public static string Home_TabelaJogos_menu {
            get {
                return ResourceManager.GetString("Home_TabelaJogos_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolão TI.
        /// </summary>
        public static string Home_Titulo_menu {
            get {
                return ResourceManager.GetString("Home_Titulo_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Usuario.
        /// </summary>
        public static string Usuario_Editar_Menu {
            get {
                return ResourceManager.GetString("Usuario_Editar_Menu", resourceCulture);
            }
        }
    }
}
