//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolaoTI.Resources.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BolaoTI.Resources.View.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao realizar a aposta!.
        /// </summary>
        public static string Alert_ApostaRealiza_Invalida {
            get {
                return ResourceManager.GetString("Alert_ApostaRealiza_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aposta realizada com sucesso!.
        /// </summary>
        public static string Alert_ApostaRealiza_Sucesso {
            get {
                return ResourceManager.GetString("Alert_ApostaRealiza_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase fechada com sucesso!.
        /// </summary>
        public static string Alert_Fase_Fechada_Sucesso {
            get {
                return ResourceManager.GetString("Alert_Fase_Fechada_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido realizar apostas. Período para realização das apostas: {0} até {1}..
        /// </summary>
        public static string Alert_Fase_PeriodoInvalido {
            get {
                return ResourceManager.GetString("Alert_Fase_PeriodoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase sem partidas.
        /// </summary>
        public static string Alert_Fase_SemPartidas {
            get {
                return ResourceManager.GetString("Alert_Fase_SemPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja adicionar esse usuario como participante?.
        /// </summary>
        public static string Confirm_Deseja_AddParticipante {
            get {
                return ResourceManager.GetString("Confirm_Deseja_AddParticipante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja excluir esse registro?.
        /// </summary>
        public static string Confirm_Deseja_Exlcluir {
            get {
                return ResourceManager.GetString("Confirm_Deseja_Exlcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja reiniciar a senha desse usuario?.
        /// </summary>
        public static string Confirm_Deseja_ReiniciarSenha {
            get {
                return ResourceManager.GetString("Confirm_Deseja_ReiniciarSenha", resourceCulture);
            }
        }
    }
}
